#!/usr/bin/env bun
/**
 * Regenerates src/version.ts from package.json before every build.
 * Runs automatically via the `prebuild` npm script.
 */

import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = join(__dirname, "..");

const pkgPath = join(repoRoot, "package.json");
const versionPath = join(repoRoot, "src", "version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as { version: string };

const contents = `// This file is regenerated by scripts/generate-version.ts before every build.
// The committed value here is a fallback so fresh clones type-check without
// having to run the generator first.
export const VERSION = "${pkg.version}";
`;

writeFileSync(versionPath, contents);
console.log(`Generated src/version.ts with version ${pkg.version}`);
