// This file is regenerated by scripts/generate-version.ts before every build.
// The committed value here is a fallback so fresh clones type-check without
// having to run the generator first.
export const VERSION = "0.2.1";
